image: golang:1.15.2

cache:
  paths:
    - /go/pkg
    - /go/bin

stages:
  - build

before_script:
  - apt-get update
  - apt-get install -y upx

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - FreeNitori
    expire_in: 1 week