image: golang:1.15.2

variables:
  GOPATH: "$PWD/build/go"

cache:
  key: FeelsKappa
  paths:
    - build/go/

stages:
  - build

build:
  stage: build
  script:
    - make;
    - mkdir build/plugins/; cp plugins/*.so build/plugins
    - cd build; tar zcf freenitori.tar.gz freenitori* plugins/*.so; cd ../
  artifacts:
    paths:
      - build/freenitori.tar.gz
    expire_in: 1 week
