image: golang:1.15.2

cache:
  paths:
    - /go/pkg
    - /go/bin

stages:
  - build

build:
  stage: build
  script:
    - make
    - tar zcf /tmp/freenitori.tar.gz build/freenitori*
    - cp /tmp/freenitori.tar.gz build/
  artifacts:
    paths:
      - build/freenitori.tar.gz
    expire_in: 1 week