image: golang:1.16.3

cache:
  key: FeelsKappa
  paths:
    - build/go/

stages:
  - build

build:
  stage: build
  script:
    - GOPATH=$PWD/build/go make;
    - cd build; tar zcf freenitori.tar.gz freenitori nitorictl; cd ../
  artifacts:
    paths:
      - build/freenitori.tar.gz
    expire_in: 1 week
