image: golang:1.15.2

cache:
  paths:
    - /go/pkg
    - /go/bin

stages:
  - build

build:
  stage: build
  script:
    - make;
    - mkdir build/plugins/; cp plugins/*.so build/plugins
    - cd build; tar zcf /tmp/freenitori.tar.gz freenitori*; cd ../
    - cp /tmp/freenitori.tar.gz build/
  artifacts:
    paths:
      - build/freenitori.tar.gz
    expire_in: 1 week